[package]
name = "vector-engine"
version = "0.0.0"
description = "A programatic editor"
authors = ["you"]
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
pretty_env_logger = "0.4"
ash = { version = "0.38.0", features = ["linked", "debug"] }
png = "0.17.13"
cgmath = "0.18.0"
deno_core = "0.231.0"
deno_ast = { version = "1.0.1", features = ["transpiling"] }
tokio = { version = "1.36.0", features = ["full"] }
notify = "6.1.1"
image = "0.24.9"
gif = "=0.13.1"
